[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `cassandra` feature to include Cassandra configuration in your project:
----
$ mn create-app my-app --features cassandra
----
====

To enable the Cassandra configuration, add the following dependency to your application:

dependency:io.micronaut.configuration:micronaut-cassandra[version="{version}"]

Micronaut supports Cassandra configuration by using the https://docs.datastax.com/en/developer/java-driver/[Datastax Java Driver].
Configuration values can be supplied a property source such as below. The property name is derived from the builder methods in
https://docs.datastax.com/en/drivers/java/4.4/com/datastax/oss/driver/api/core/CqlSessionBuilder.html[CqlSessionBuilder].
Micronaut will create a https://docs.datastax.com/en/drivers/java/4.4/com/datastax/oss/driver/api/core/CqlSession.html[CqlSession] bean. This bean
can be then injected into any other Micronaut bean.

.Supply Single Configuration
[source,yaml]
----
cassandra:
  default:
    advanced:
      metadata:
        schema:
          enabled: false
    basic:
      contact-points:
        - "127.0.0.1:9042"
        - "127.0.0.2:8042"
      load-balancing-policy:
        local-datacenter: datacenter1
----

Multiple Cluster instances can be configured as follows:

.Supply Multiple Configuration
[source,yaml]
----
cassandra:
  default:
    advanced:
      metadata:
        schema:
          enabled: false
    basic:
      contact-points:
        - "127.0.0.1:9042"
      load-balancing-policy:
        local-datacenter: datacenter1
  secondary:
    advanced:
      metadata:
        schema:
          enabled: false
    basic:
      contact-points:
        - "127.0.0.1:9043"
      load-balancing-policy:
        local-datacenter: datacenter2
----

