[versions]
managed-datastax-cassandra-driver = "4.15.0"

groovy = "4.0.9"
micronaut-test = "4.0.0-SNAPSHOT"
spock = "2.3-groovy-4.0"
testcontainers = "1.17.6"

[libraries]
managed-datastax-cassandra-driver-core = { module = "com.datastax.oss:java-driver-core", version.ref = "managed-datastax-cassandra-driver" }
managed-datastax-cassandra-driver-mapper-processor = { module = "com.datastax.oss:java-driver-mapper-processor", version.ref = "managed-datastax-cassandra-driver" }

testcontainers-cassandra = { module = "org.testcontainers:cassandra", version.ref = "testcontainers" }
testcontainers-spock = { module = "org.testcontainers:spock", version.ref = "testcontainers" }
