[versions]
cassandra = "1.15.3"
datastax-cassandra-driver = "4.11.1"
testcontainers-spock = "1.16.3"

# Micronaut
micronaut-docs = "2.0.0"
micronaut-test = "3.0.3"


[libraries]
# Micronaut
micronaut-docs-asciidoc-config-props = { module = "io.micronaut.docs:micronaut-docs-asciidoc-config-props", version.ref = "micronaut-docs" }
micronaut-inject = { module = "io.micronaut:micronaut-inject" }
micronaut-inject-groovy = { module = "io.micronaut:micronaut-inject-groovy" }
micronaut-inject-java = { module = "io.micronaut:micronaut-inject-java" }
micronaut-management = { module = "io.micronaut:micronaut-management" }
micronaut-test-spock = { module = "io.micronaut.test:micronaut-test-spock", version.ref = "micronaut-test" }

cassandra = { module = "org.testcontainers:cassandra", version.ref = "cassandra" }
java-driver-core = { module = "com.datastax.oss:java-driver-core", version.ref = "datastax-cassandra-driver" }
java-driver-mapper-processor = { module = "com.datastax.oss:java-driver-mapper-processor", version.ref = "datastax-cassandra-driver" }
reactor-core = { module = "io.projectreactor:reactor-core" }
testcontainers-spock = { module = "org.testcontainers:spock", version.ref = "testcontainers-spock" }
