[versions]
micronaut = "5.0.0-M26"
micronaut-test = "5.0.0-M8"
micronaut-platform = "5.0.0-M2"
micronaut-reactor = "4.0.0-M2"
micronaut-micrometer = "6.0.1-M1"
micronaut-gradle-plugin = "5.0.0-M1"
managed-datastax-cassandra-driver = "4.17.0"

system-stubs = "2.1.8"
bcpkix = "1.84"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor-bom", version.ref = "micronaut-reactor" }
managed-datastax-cassandra-driver-core = { module = "com.datastax.oss:java-driver-core", version.ref = "managed-datastax-cassandra-driver" }
managed-datastax-cassandra-driver-mapper-processor = { module = "com.datastax.oss:java-driver-mapper-processor", version.ref = "managed-datastax-cassandra-driver" }
managed-datastax-cassandra-driver-metrics-micrometer = { module = "com.datastax.oss:java-driver-metrics-micrometer", version.ref = "managed-datastax-cassandra-driver" }

bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bcpkix" }
system-stubs = { module = "uk.org.webcompere:system-stubs-core", version.ref = "system-stubs" }
testcontainers-cassandra = { module = "org.testcontainers:testcontainers-cassandra" }
testcontainers = { module = "org.testcontainers:testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter"}
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
